### PR TITLE
Add basic Shell, Event, and WebContents support

### PR DESCRIPTION
**Pull request by maddie927**
I've still got more to do, so don't feel like you should address this PR right away.  I just wanted to make you aware of it since we both added WebContents : ]

### CODE REVIEW

**Comment by maddie927** [comment]
I'm also kinda new to this, so I appreciate any feedback on the code

**Comment by bamboo** [comment]
Awesome!

I had to [change some things](https://github.com/bamboo/purescript-electron/commit/710903a3b065f8f0eb16ac005edadea21dcfa641) to compile it against 0.7.6.1. I assume you're already on 0.8? 

Except for those the code looks good to me and I'd be happy to merge a 0.7 compatible version of the PR.

**Comment by maddie927** [comment]
Hey, now that 0.8 is out, do you think it still makes sense to make these changes for 0.7?

**Comment by bamboo** [comment]
No, 0.8 looks good, let's use it.

**Comment by bamboo** [comment]
Thanks!

**Pull request merged**
